# -*- coding: utf-8 -*-
"""estimasi_paru-paru.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJTiwPOyLMrqw_2Uev8uVUgmaI40eFMF
"""

import pickle
import streamlit as st

model = pickle.load(open('estimasi_paru-paru.sav', 'rb'))

st.title('Estimasi Pasien Yang Terkena Penyakit Kanker Paru-Paru')

AGEt = st.number_input('Input Usia Pasien')
SMOKING = st.number_input('Input Pasien Merokok atau Tidak')
YELLOW_FINGER = st.number_input('Input Jumlah Gula')
ANXIETY = st.number_input('Input Jumlah Kolestrol')
PEER_PRESSURE = st.number_input('Input Jumlah Sodium')
CHRONIC DISEASE = st.number_input('Input Jumlah Kalori')
WHEEZING = st.number_input('Input Jumlah Karbohidrat')
ALCOHOL CONSUMING = st.number_input('Input Jumlah Karbohidrat')
COUGHING = st.number_input('Input Jumlah Karbohidrat')
SHORTNESS OF BREATH = st.number_input('Input Jumlah Karbohidrat')
SWALLOWING DIFFICULTY = st.number_input('Input Jumlah Karbohidrat')
CHEST PAIN = st.number_input('Input Jumlah Karbohidrat')

predict = ''

if st.button('Estimasi: '):
    predict = model.predict(
        [[AGE, SMOKING, YELLOW_FINGERS, ANXIETY, PEER_PRESSURE, CHRONIC DISEASE, WHEEZING, ALCOHOL CONSUMING, COUGHING, SHORTNESS OF BREATH, SWALLOWING DIFFICULTY, CHEST PAIN]]
    )
    st.write('Estimasi Apakah Pasien Terkena Penyakit Kanker Paru-Paru? : ', predict)